/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto;

/**
 *
 * @author davidazullo
 */
public class BuscarSocio extends javax.swing.JPanel {

    /**
     * Creates new form BuscarChamba
     */
    public BuscarSocio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JLabel();
        CamposDeTrabajo = new javax.swing.JComboBox<>();
        CampoTrabajo = new javax.swing.JLabel();
        Instrucciones = new javax.swing.JLabel();
        Prestaciones = new javax.swing.JCheckBox();
        TPrestaciones = new javax.swing.JLabel();
        Enviar = new javax.swing.JButton();
        ExperienciaTitulo = new javax.swing.JLabel();
        TExperiencia = new javax.swing.JLabel();
        Experiencia = new javax.swing.JSpinner();

        Titulo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("Buscador de Socios");

        CamposDeTrabajo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tecnologías de la información",
            "Mercadotecnía",
            "Industria",
            "Administración de empresas" }));

CampoTrabajo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
CampoTrabajo.setText("Especialidad");

Instrucciones.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
Instrucciones.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
Instrucciones.setText("Complete los siguientes campos para realizar su búsqueda");

Prestaciones.setText("Sí");
Prestaciones.addActionListener(new java.awt.event.ActionListener() {
    public void actionPerformed(java.awt.event.ActionEvent evt) {
        PrestacionesActionPerformed(evt);
    }
    });

    TPrestaciones.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    TPrestaciones.setText("¿Empresario?");

    Enviar.setText("Subir solicitud");

    ExperienciaTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    ExperienciaTitulo.setText("Cantidad de capital que está dispuesto a invertir");

    TExperiencia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    TExperiencia.setText("Monto");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(Titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(255, 255, 255))
                .addGroup(layout.createSequentialGroup()
                    .addComponent(CampoTrabajo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(415, 415, 415))
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Instrucciones, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CamposDeTrabajo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(176, 176, 176)
                                .addComponent(Enviar))
                            .addComponent(Prestaciones, javax.swing.GroupLayout.Alignment.LEADING))
                        .addComponent(TPrestaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ExperienciaTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(TExperiencia)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Experiencia, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 0, Short.MAX_VALUE))))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(Titulo)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(Instrucciones)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(CampoTrabajo)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(CamposDeTrabajo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(TPrestaciones)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(Prestaciones)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(ExperienciaTitulo)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(TExperiencia)
                .addComponent(Experiencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(10, 10, 10)
            .addComponent(Enviar)
            .addContainerGap())
    );
    }// </editor-fold>//GEN-END:initComponents

    private void PrestacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrestacionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PrestacionesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CampoTrabajo;
    private javax.swing.JComboBox<String> CamposDeTrabajo;
    private javax.swing.JButton Enviar;
    private javax.swing.JSpinner Experiencia;
    private javax.swing.JLabel ExperienciaTitulo;
    private javax.swing.JLabel Instrucciones;
    private javax.swing.JCheckBox Prestaciones;
    private javax.swing.JLabel TExperiencia;
    private javax.swing.JLabel TPrestaciones;
    private javax.swing.JLabel Titulo;
    // End of variables declaration//GEN-END:variables
}
