package proyecto;

import javax.swing.JFrame;

/**
 *
 * @author davidazullo
 */
public class Empleador extends ContenidoPanel {

    /**
     * Creates new form Socio
     */
    public Empleador(JFrame ventana) {
        super(ventana);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JLabel();
        BuscaChambeador = new javax.swing.JButton();
        BuscaSocio = new javax.swing.JButton();
        SubirProyecto = new javax.swing.JButton();
        CalificaEmpleado = new javax.swing.JButton();
        Salir = new javax.swing.JButton();
        CambiarPassword = new javax.swing.JButton();
        BuscarCursos = new javax.swing.JButton();

        Titulo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("Empleador");

        BuscaChambeador.setText("Buscar Chambeador");

        BuscaSocio.setText("Buscar Socio");

        SubirProyecto.setText("Subir proyecto");

        CalificaEmpleado.setText("Calificar Empleado");

        Salir.setText("Salir");

        CambiarPassword.setText("Cambiar contraseña");
        CambiarPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CambiarPasswordActionPerformed(evt);
            }
        });

        BuscarCursos.setText("Buscar cursos");
        BuscarCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarCursosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BuscaChambeador)
                            .addComponent(CalificaEmpleado)
                            .addComponent(CambiarPassword))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SubirProyecto)
                            .addComponent(BuscaSocio)
                            .addComponent(Salir)))
                    .addComponent(BuscarCursos))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BuscaChambeador)
                    .addComponent(BuscaSocio))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SubirProyecto)
                    .addComponent(CalificaEmpleado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BuscarCursos)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Salir)
                    .addComponent(CambiarPassword))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void CambiarPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CambiarPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CambiarPasswordActionPerformed

    private void BuscarCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarCursosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BuscarCursosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BuscaChambeador;
    private javax.swing.JButton BuscaSocio;
    private javax.swing.JButton BuscarCursos;
    private javax.swing.JButton CalificaEmpleado;
    private javax.swing.JButton CambiarPassword;
    private javax.swing.JButton Salir;
    private javax.swing.JButton SubirProyecto;
    private javax.swing.JLabel Titulo;
    // End of variables declaration//GEN-END:variables
}
