package paneles;

import java.io.File;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author davidazullo
 */
public class CalificarEmpleador extends ContenidoPanel {

    /**
     * Creates new form CalificarEmpleado
     */
    public CalificarEmpleador(ContenidoJFrame ventana) {
        super(ventana);
        Empresa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ejemplo" }));
        ArrayList<String> usuarios = encuentraUsuarios();
        for(String f : usuarios){
            Empresa.addItem(f);
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JLabel();
        Instrucciones = new javax.swing.JLabel();
        TEmpresa = new javax.swing.JLabel();
        Empresa = new javax.swing.JComboBox<>();
        Horario = new javax.swing.JSlider();
        THorario = new javax.swing.JLabel();
        Prestaciones = new javax.swing.JSlider();
        TPrestaciones = new javax.swing.JLabel();
        Vacaciones = new javax.swing.JSlider();
        TVacaciones = new javax.swing.JLabel();
        Enviar = new javax.swing.JButton();

        Titulo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("Calificar Empleador");

        Instrucciones.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        Instrucciones.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Instrucciones.setText("Complete los siguientes campos para realizar la calificación");

        TEmpresa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TEmpresa.setText("Empresa");

        Empresa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ejemplo" }));

        THorario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        THorario.setText("Horario");

        TPrestaciones.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TPrestaciones.setText("Prestaciones");

        TVacaciones.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TVacaciones.setText("Vacaciones");

        Enviar.setText("Calificar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Instrucciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TEmpresa)
                            .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Horario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(THorario)
                            .addComponent(Prestaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TPrestaciones)
                            .addComponent(Vacaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TVacaciones)
                            .addComponent(Enviar)
                            .addComponent(Empresa, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Instrucciones)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TEmpresa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Empresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(THorario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Horario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TPrestaciones)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Prestaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TVacaciones)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Vacaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(Enviar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    public ArrayList<String> encuentraUsuarios(){
        ArrayList<String> usuarios = new ArrayList<>();
            File f = new File(System.getProperty("user.dir"));
            if(f.exists()){
                File[] ficheros = f.listFiles(); 
                for (File fichero : ficheros) {
                    String temp = fichero.getName();
                    if(temp.endsWith(".dat")){
                        String archivo = temp.substring(0, temp.length()-4);
                        Archivo empleador = new Archivo(archivo);
                        Usuario temporal = empleador.leeArchivo();
                        if(temporal.getTipo().equals("Empleador"))
                            usuarios.add(temporal.getNombre());
                    }
                }
            }
            if(usuarios.isEmpty())
                JOptionPane.showMessageDialog(null, "No hay empleados registrados", "", JOptionPane.INFORMATION_MESSAGE);
            return usuarios;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Empresa;
    private javax.swing.JButton Enviar;
    private javax.swing.JSlider Horario;
    private javax.swing.JLabel Instrucciones;
    private javax.swing.JSlider Prestaciones;
    private javax.swing.JLabel TEmpresa;
    private javax.swing.JLabel THorario;
    private javax.swing.JLabel TPrestaciones;
    private javax.swing.JLabel TVacaciones;
    private javax.swing.JLabel Titulo;
    private javax.swing.JSlider Vacaciones;
    // End of variables declaration//GEN-END:variables
}
