package paneles;
import elementos.Archivo;
import elementos.Chambapp;
import elementos.Utilerias;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 * Clase que se encarga de almacenar los comentarios
 * y sugerencias de sus usuarios
 */
public class Comentarios extends ContenidoPanel {

    /**
     * Constructor de la interfaz de usuario COmentarios
     * @param ventana
     */
    public Comentarios(ContenidoJFrame ventana) {
        super(ventana);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JLabel();
        Instrucciones = new javax.swing.JLabel();
        Instrucciones2 = new javax.swing.JLabel();
        Comentarios = new javax.swing.JTextField();
        Enviar = new javax.swing.JButton();
        Cancelar = new javax.swing.JButton();

        Titulo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("Comentarios y feedback");

        Instrucciones.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Instrucciones.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Instrucciones.setText("Inserte sus comentarios acerca de nuestra aplicación y diganos");

        Instrucciones2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Instrucciones2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Instrucciones2.setText("en que le gustaría que mejoraramos");

        Enviar.setText("Aceptar");
        Enviar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EnviarMouseClicked(evt);
            }
        });

        Cancelar.setText("Cancelar");
        Cancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CancelarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(Comentarios)
                        .addComponent(Instrucciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Instrucciones2, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Titulo, javax.swing.GroupLayout.Alignment.LEADING))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Enviar)
                        .addGap(50, 50, 50)
                        .addComponent(Cancelar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Instrucciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Instrucciones2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Comentarios, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Enviar)
                    .addComponent(Cancelar))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void EnviarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EnviarMouseClicked
        Chambapp chambapp = this.getChambapp();
        Archivo fichero = new Archivo(this.getChambapp().getRutaComentarios());
        if(fichero.existe())
            chambapp.setComentarios(fichero.leeComentarios());
        if(chambapp.getComentarios() == null)
            chambapp.setComentarios(new ArrayList<String>());
        String comentario = Comentarios.getText();
        String mensaje;
        if(chambapp.getComentarios().isEmpty())
            mensaje = "Usted ha sido el primero en proporcionarnos feedback, gracias ;).";
        else {
            mensaje = "Gracias por su feedback, el penultimo comentario fue: '";
            mensaje += chambapp.getComentarios().get(chambapp.getComentarios().size()-1);
            mensaje += "' y con el suyo suman ya "+(chambapp.getComentarios().size()+1);
            mensaje += " comentarios";
        }
        chambapp.addComentario(comentario);
        Archivo nuevo;
        nuevo = new Archivo(chambapp.getComentarios(), chambapp.getRutaComentarios());
        nuevo.escribeComentarios();
        JOptionPane.showMessageDialog(null, mensaje, "", JOptionPane.INFORMATION_MESSAGE);
        Utilerias.cambiaComponentePadre(this);
    }//GEN-LAST:event_EnviarMouseClicked

    private void CancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelarMouseClicked
        Utilerias.cambiaComponentePadre(this);
    }//GEN-LAST:event_CancelarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancelar;
    private javax.swing.JTextField Comentarios;
    private javax.swing.JButton Enviar;
    private javax.swing.JLabel Instrucciones;
    private javax.swing.JLabel Instrucciones2;
    private javax.swing.JLabel Titulo;
    // End of variables declaration//GEN-END:variables
}
