package paneles;

import javax.swing.JFrame;

/**
 *
 * @author davidazullo
 */
public class CursosTomados extends ContenidoPanel {

    /**
     * Creates new form CursosDisponibles
     */
    public CursosTomados(ContenidoJFrame ventana) {
        super(ventana);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Descripcion = new javax.swing.JLabel();
        Curso1 = new javax.swing.JLabel();
        Curso2 = new javax.swing.JLabel();
        Intrucciones1 = new javax.swing.JLabel();
        Instrucciones2 = new javax.swing.JLabel();
        Intrucciones3 = new javax.swing.JLabel();
        Horario1 = new javax.swing.JLabel();
        Horario2 = new javax.swing.JLabel();

        Titulo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("Cursos");

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Descripcion.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Descripcion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Descripcion.setText("Usted ha seleccionado los siguientes cursos:");

        Curso1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Curso1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Curso1.setText("* Creación de un Modelo Canvas");

        Curso2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Curso2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Curso2.setText("* Cómo declarar impuestos ante el SAT");

        Intrucciones1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Intrucciones1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Intrucciones1.setText("Se le notifica que ambos cursos inician sesión el 25 de mayo y");

        Instrucciones2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Instrucciones2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Instrucciones2.setText("se terminan el 12 de junio del año presente, el horario de clases");

        Intrucciones3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Intrucciones3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Intrucciones3.setText("es el siguiente:");

        Horario1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Horario1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Horario1.setText("* Creación de un Modelo Canvas, martes y jueves de 12:00 a 14:00 hrs, $2000");

        Horario2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Horario2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Horario2.setText("* Cómo declarar impuestos ante el SAT, sábados de 8:00 a 14:00 hrs, $3500");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Descripcion)
                    .addComponent(Curso1)
                    .addComponent(Curso2)
                    .addComponent(Intrucciones1)
                    .addComponent(Instrucciones2)
                    .addComponent(Intrucciones3)
                    .addComponent(Horario1)
                    .addComponent(Horario2))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Descripcion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Curso1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Curso2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Intrucciones1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Instrucciones2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Intrucciones3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Horario1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Horario2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(47, 47, 47)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Curso1;
    private javax.swing.JLabel Curso2;
    private javax.swing.JLabel Descripcion;
    private javax.swing.JLabel Horario1;
    private javax.swing.JLabel Horario2;
    private javax.swing.JLabel Instrucciones2;
    private javax.swing.JLabel Intrucciones1;
    private javax.swing.JLabel Intrucciones3;
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
