package paneles;

import elementos.Utilerias;
import static java.lang.System.exit;

/**
 * Clase que muestra las acciones disponibles del empleador
 */
public class Empleador extends ContenidoPanel {

    /**
     * Constructor de empleador
     * @param ventana
     */
    public Empleador(ContenidoJFrame ventana) {
        super(ventana);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JLabel();
        BuscaChambeador = new javax.swing.JButton();
        BuscaSocio = new javax.swing.JButton();
        SubirProyecto = new javax.swing.JButton();
        CalificaEmpleado = new javax.swing.JButton();
        Salir = new javax.swing.JButton();
        CambiarPassword = new javax.swing.JButton();
        BuscarCursos = new javax.swing.JButton();

        Titulo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("Empleador");

        BuscaChambeador.setText("Buscar Chambeador");
        BuscaChambeador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BuscaChambeadorMouseClicked(evt);
            }
        });

        BuscaSocio.setText("Buscar Socio");
        BuscaSocio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BuscaSocioMouseClicked(evt);
            }
        });

        SubirProyecto.setText("Subir proyecto");
        SubirProyecto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SubirProyectoMouseClicked(evt);
            }
        });

        CalificaEmpleado.setText("Calificar Empleado");
        CalificaEmpleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CalificaEmpleadoMouseClicked(evt);
            }
        });

        Salir.setText("Salir");
        Salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SalirMouseClicked(evt);
            }
        });

        CambiarPassword.setText("Cambiar contraseña");
        CambiarPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CambiarPasswordMouseClicked(evt);
            }
        });

        BuscarCursos.setText("Buscar cursos");
        BuscarCursos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BuscarCursosMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BuscaChambeador)
                            .addComponent(CalificaEmpleado)
                            .addComponent(CambiarPassword))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SubirProyecto)
                            .addComponent(BuscaSocio)
                            .addComponent(Salir)))
                    .addComponent(BuscarCursos))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BuscaChambeador)
                    .addComponent(BuscaSocio))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SubirProyecto)
                    .addComponent(CalificaEmpleado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BuscarCursos)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Salir)
                    .addComponent(CambiarPassword))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BuscaChambeadorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BuscaChambeadorMouseClicked
        Utilerias.muestraComponente( this.getPadre(), new BuscarChambeador(this.getPadre()) );
    }//GEN-LAST:event_BuscaChambeadorMouseClicked

    private void BuscaSocioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BuscaSocioMouseClicked
        Utilerias.muestraComponente( this.getPadre(), new BuscarSocio(this.getPadre()) );
    }//GEN-LAST:event_BuscaSocioMouseClicked

    private void CalificaEmpleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CalificaEmpleadoMouseClicked
        Utilerias.muestraComponente( this.getPadre(), new CalificarEmpleado(this.getPadre()) );
    }//GEN-LAST:event_CalificaEmpleadoMouseClicked

    private void SubirProyectoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubirProyectoMouseClicked
        Utilerias.muestraComponente( this.getPadre(), new SubirProyecto(this.getPadre()) );
    }//GEN-LAST:event_SubirProyectoMouseClicked

    private void BuscarCursosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BuscarCursosMouseClicked
        Utilerias.muestraComponente( this.getPadre(), new MostrarCursos(this.getPadre()) );
    }//GEN-LAST:event_BuscarCursosMouseClicked

    private void SalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalirMouseClicked
        exit(0);
    }//GEN-LAST:event_SalirMouseClicked

    private void CambiarPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CambiarPasswordMouseClicked
        Utilerias.muestraComponente( this.getPadre(), new CambioContrasena(this.getPadre()) );
    }//GEN-LAST:event_CambiarPasswordMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BuscaChambeador;
    private javax.swing.JButton BuscaSocio;
    private javax.swing.JButton BuscarCursos;
    private javax.swing.JButton CalificaEmpleado;
    private javax.swing.JButton CambiarPassword;
    private javax.swing.JButton Salir;
    private javax.swing.JButton SubirProyecto;
    private javax.swing.JLabel Titulo;
    // End of variables declaration//GEN-END:variables
}
