package paneles;

import java.io.File;
import static java.lang.System.exit;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 * Clase que muestra las acciones disponibles del empleador
 */
public class Empleador extends ContenidoPanel {

    /**
     * Constructor de empleador
     * @param ventana
     */
    public Empleador(ContenidoJFrame ventana) {
        super(ventana);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JLabel();
        BuscaChambeador = new javax.swing.JButton();
        BuscaSocio = new javax.swing.JButton();
        SubirProyecto = new javax.swing.JButton();
        CalificaEmpleado = new javax.swing.JButton();
        Salir = new javax.swing.JButton();
        CambiarPassword = new javax.swing.JButton();
        BuscarCursos = new javax.swing.JButton();
        CamposExtra = new javax.swing.JButton();
        BuscarProyecto = new javax.swing.JButton();
        CerrarSesion = new javax.swing.JButton();

        Titulo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("Empleador");

        BuscaChambeador.setText("Buscar Chambeador");
        BuscaChambeador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BuscaChambeadorMouseClicked(evt);
            }
        });

        BuscaSocio.setText("Buscar Socio");
        BuscaSocio.setToolTipText("Saldrá en la versión 2.0");
        BuscaSocio.setEnabled(false);
        BuscaSocio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BuscaSocioMouseClicked(evt);
            }
        });

        SubirProyecto.setText("Subir proyecto");
        SubirProyecto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SubirProyectoMouseClicked(evt);
            }
        });

        CalificaEmpleado.setText("Calificar Empleado");
        CalificaEmpleado.setToolTipText("Saldrá en la versión 2.0");
        CalificaEmpleado.setEnabled(false);
        CalificaEmpleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CalificaEmpleadoMouseClicked(evt);
            }
        });

        Salir.setText("Salir");
        Salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SalirMouseClicked(evt);
            }
        });

        CambiarPassword.setText("Cambiar contraseña");
        CambiarPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CambiarPasswordMouseClicked(evt);
            }
        });

        BuscarCursos.setText("Buscar cursos");
        BuscarCursos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BuscarCursosMouseClicked(evt);
            }
        });

        CamposExtra.setText("Añadir Campos Extra");
        CamposExtra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CamposExtraActionPerformed(evt);
            }
        });

        BuscarProyecto.setText("Buscar Proyecto");
        BuscarProyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarProyectoActionPerformed(evt);
            }
        });

        CerrarSesion.setText("Cerrar Sesión");
        CerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CerrarSesionMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(BuscarProyecto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BuscaChambeador, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CambiarPassword, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BuscarCursos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CalificaEmpleado, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(SubirProyecto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CamposExtra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BuscaSocio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CerrarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Salir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BuscaChambeador)
                    .addComponent(BuscaSocio))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SubirProyecto)
                    .addComponent(CalificaEmpleado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BuscarCursos)
                    .addComponent(CamposExtra))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BuscarProyecto)
                    .addComponent(CerrarSesion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Salir)
                    .addComponent(CambiarPassword))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BuscaChambeadorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BuscaChambeadorMouseClicked
        Utilerias.muestraComponente( this.getPadre(), new BuscarChambeador(this.getPadre()) );
    }//GEN-LAST:event_BuscaChambeadorMouseClicked

    private void BuscaSocioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BuscaSocioMouseClicked
        Utilerias.muestraComponente( this.getPadre(), new BuscarSocio(this.getPadre()) );
    }//GEN-LAST:event_BuscaSocioMouseClicked

    private void CalificaEmpleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CalificaEmpleadoMouseClicked
        Utilerias.muestraComponente( this.getPadre(), new CalificarEmpleado(this.getPadre()) );
    }//GEN-LAST:event_CalificaEmpleadoMouseClicked

    private void SubirProyectoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubirProyectoMouseClicked
        Utilerias.muestraComponente( this.getPadre(), new SubirProyecto(this.getPadre()) );
    }//GEN-LAST:event_SubirProyectoMouseClicked

    private void BuscarCursosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BuscarCursosMouseClicked
        Utilerias.muestraComponente( this.getPadre(), new MostrarCursos(this.getPadre()) );
    }//GEN-LAST:event_BuscarCursosMouseClicked

    private void SalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalirMouseClicked
        exit(0);
    }//GEN-LAST:event_SalirMouseClicked

    private void CambiarPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CambiarPasswordMouseClicked
        Utilerias.muestraComponente( this.getPadre(), new CambioContrasena(this.getPadre()) );
    }//GEN-LAST:event_CambiarPasswordMouseClicked

    private void CamposExtraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CamposExtraActionPerformed
        Utilerias.muestraComponente( this.getPadre(), new EmpleadorAdicional(this.getPadre()) );
    }//GEN-LAST:event_CamposExtraActionPerformed

    private void BuscarProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarProyectoActionPerformed
        float monto = Float.parseFloat(JOptionPane.showInputDialog("Ingrese el presupuesto de proyecto: "));
        ArrayList<Proyecto> proyectos = new ArrayList<>();
            File f = new File(System.getProperty("user.dir"));
            if(f.exists()){
                File[] ficheros = f.listFiles(); 
                for (File fichero : ficheros) {
                    String temp = fichero.getName();
                    if(temp.endsWith(".dat")){
                        String archivo = temp.substring(0, temp.length()-4);
                        Archivo empleador = new Archivo(archivo);
                        Usuario temporal = empleador.leeArchivo();
                        Proyecto project = temporal.getProyecto();
                        if(project.getMonto() <= monto && project.getMonto() >= 1)
                            proyectos.add(project);
                    }
                }
            }
            if(proyectos.isEmpty()){
                JOptionPane.showMessageDialog(null, "No Hay Proyecto Con El Monto Especificado", "", JOptionPane.INFORMATION_MESSAGE);
            }
            else{
                String cad = "Proyectos Que Cumplen Con El Monto Solicitado: \n";
                for(Proyecto p : proyectos){
                    cad += Utilerias.convierteACadena(p);
                }
                JOptionPane.showMessageDialog(null, cad, "", JOptionPane.INFORMATION_MESSAGE);
            }
    }//GEN-LAST:event_BuscarProyectoActionPerformed

    private void CerrarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CerrarSesionMouseClicked
        this.getPadre().setVisible(false);
        Menu menu = new Menu(this.getChambapp());
        menu.setVisible(true);
        menu.setLocationRelativeTo(null);
    }//GEN-LAST:event_CerrarSesionMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BuscaChambeador;
    private javax.swing.JButton BuscaSocio;
    private javax.swing.JButton BuscarCursos;
    private javax.swing.JButton BuscarProyecto;
    private javax.swing.JButton CalificaEmpleado;
    private javax.swing.JButton CambiarPassword;
    private javax.swing.JButton CamposExtra;
    private javax.swing.JButton CerrarSesion;
    private javax.swing.JButton Salir;
    private javax.swing.JButton SubirProyecto;
    private javax.swing.JLabel Titulo;
    // End of variables declaration//GEN-END:variables
}
