package paneles;

import javax.swing.JFrame;

/**
 *
 * @author davidazullo
 */
public class Empleado extends ContenidoPanel {

    /**
     * Creates new form Socio
     */
    public Empleado(JFrame ventana) {
        super(ventana);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JLabel();
        BuscaChamba = new javax.swing.JButton();
        BuscaSocio = new javax.swing.JButton();
        SubirProyecto = new javax.swing.JButton();
        CalificarEmpleador = new javax.swing.JButton();
        Salir = new javax.swing.JButton();
        CambiaPassword = new javax.swing.JButton();
        BuscarCursos = new javax.swing.JButton();
        CamposExtra = new javax.swing.JButton();

        Titulo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("Empleado");

        BuscaChamba.setText("Buscar Chamba");

        BuscaSocio.setText("Buscar Socio");

        SubirProyecto.setText("Subir proyecto");

        CalificarEmpleador.setText("Calificar Empleador");

        Salir.setText("Salir");

        CambiaPassword.setText("Cambiar contraseña");
        CambiaPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CambiaPasswordActionPerformed(evt);
            }
        });

        BuscarCursos.setText("Buscar cursos");
        BuscarCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarCursosActionPerformed(evt);
            }
        });

        CamposExtra.setText("Añadir campos extra");
        CamposExtra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CamposExtraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BuscaChamba)
                            .addComponent(CalificarEmpleador)
                            .addComponent(CambiaPassword)
                            .addComponent(BuscarCursos))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CamposExtra)
                            .addComponent(SubirProyecto)
                            .addComponent(BuscaSocio)
                            .addComponent(Salir))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BuscaChamba)
                    .addComponent(BuscaSocio))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SubirProyecto)
                    .addComponent(CalificarEmpleador))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BuscarCursos)
                    .addComponent(CamposExtra))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Salir)
                    .addComponent(CambiaPassword))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void CambiaPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CambiaPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CambiaPasswordActionPerformed

    private void BuscarCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarCursosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BuscarCursosActionPerformed

    private void CamposExtraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CamposExtraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CamposExtraActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BuscaChamba;
    private javax.swing.JButton BuscaSocio;
    private javax.swing.JButton BuscarCursos;
    private javax.swing.JButton CalificarEmpleador;
    private javax.swing.JButton CambiaPassword;
    private javax.swing.JButton CamposExtra;
    private javax.swing.JButton Salir;
    private javax.swing.JButton SubirProyecto;
    private javax.swing.JLabel Titulo;
    // End of variables declaration//GEN-END:variables
}
