package paneles;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 * Clase que se encarga de mostrar los cursos disponibles al usuario
 */
public class MostrarCursos extends ContenidoPanel {

    /**
     * Constructor de la interfaz de usuario MostrarCursos
     * @param ventana
     */
    public MostrarCursos(ContenidoJFrame ventana) {
        super(ventana);
        initComponents();
    }
    
    /**
     * Método que se encarga de validar el formulario
     */
    private void validarFormulario() {
        ArrayList<String> cursosDisponibles = new ArrayList<String>();
        if(Topico1.isSelected()) {
            if(Presencial.isSelected())
                cursosDisponibles.add("ANALISIS DE SEGMENTOS DE MERCADO: LAS TRIBUS DE CONSUMIDORES EN MEXICO");
            else {
                cursosDisponibles.add("COMUNICACION DIGITAL");
                cursosDisponibles.add("EMOTIONAL & EXPERIENTIAL MARKETING");
            }
        }
        if(Topico2.isSelected()) {
            cursosDisponibles.add("IMPUESTOS INTERNACIONALES");
            cursosDisponibles.add("ANALISIS DE INVERSIONES");            
        }
        if(Topico3.isSelected() && Presencial.isSelected()) {
            cursosDisponibles.add("ARGUMENTACION");
        }
        if(Topico4.isSelected()) {
            cursosDisponibles.add("PROGRAMACION OOP EN JAVA Y C++");
            cursosDisponibles.add("UNA INTRODUCCION A LOS BITCOIN");            
        }
        if(Topico5.isSelected()) {
            cursosDisponibles.add("ALGEBRA LINEAL CON ENFOQUE EN ECONOMIA");
            if(Presencial.isSelected())
                cursosDisponibles.add("MODELOS DE PRODUCCION");            
        }
        if(!cursosDisponibles.isEmpty()) {
            String cadena = "Dadas sus preferencias, le recomendamos estos cursos,\n";
            cadena += "seleccione uno o más y envienos un mail a cursos@chambapp.com,\n";
            cadena += "se le notificará de manera oportuna los costos y fechas.\n";
            cadena += "A continuacion los cursos:\n";
            for (String curso : cursosDisponibles) 
                cadena += "\n" + curso;
            JOptionPane.showMessageDialog(null, cadena, "", JOptionPane.INFORMATION_MESSAGE);
            Utilerias.cambiaComponentePadre(this);
        }
        else JOptionPane.showMessageDialog(null, "No se encontro ningun curso acorde a sus preferencias.", "", JOptionPane.INFORMATION_MESSAGE);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JLabel();
        Instrucciones = new javax.swing.JLabel();
        Topico1 = new javax.swing.JCheckBox();
        Topico2 = new javax.swing.JCheckBox();
        Topico3 = new javax.swing.JCheckBox();
        Topico4 = new javax.swing.JCheckBox();
        Topico5 = new javax.swing.JCheckBox();
        TPresencial = new javax.swing.JLabel();
        Presencial = new javax.swing.JCheckBox();
        Enviar = new javax.swing.JButton();
        Regresar = new javax.swing.JButton();

        Titulo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("Cursos");

        Instrucciones.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Instrucciones.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Instrucciones.setText("Seleccione los tópicos de su interés");

        Topico1.setText("Mercadotecnia");

        Topico2.setText("Economía y finanzas");

        Topico3.setText("Derecho");

        Topico4.setText("Tecnología");

        Topico5.setText("Ingeniería");

        TPresencial.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        TPresencial.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TPresencial.setText("Requiere curso presencial");

        Presencial.setText("Sí");

        Enviar.setText("Aceptar");
        Enviar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EnviarMouseClicked(evt);
            }
        });

        Regresar.setText("Regresar");
        Regresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegresarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Enviar, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addComponent(Regresar, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Topico5)
                            .addComponent(Topico4)
                            .addComponent(Topico3)
                            .addComponent(Topico2)
                            .addComponent(Topico1)
                            .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Instrucciones)
                            .addComponent(Presencial)
                            .addComponent(TPresencial))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Instrucciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Topico1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Topico2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Topico3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Topico4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Topico5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TPresencial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Presencial)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Enviar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Regresar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Ejecuta la acción al presionar botón Aceptar
     * @param evt 
     */
    private void EnviarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EnviarMouseClicked
        validarFormulario();
    }//GEN-LAST:event_EnviarMouseClicked
    /**
     * Ejecuta la acción al presionar botón regresar
     * @param evt 
     */
    private void RegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegresarMouseClicked
        Utilerias.cambiaComponentePadre(this);
    }//GEN-LAST:event_RegresarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Enviar;
    private javax.swing.JLabel Instrucciones;
    private javax.swing.JCheckBox Presencial;
    private javax.swing.JButton Regresar;
    private javax.swing.JLabel TPresencial;
    private javax.swing.JLabel Titulo;
    private javax.swing.JCheckBox Topico1;
    private javax.swing.JCheckBox Topico2;
    private javax.swing.JCheckBox Topico3;
    private javax.swing.JCheckBox Topico4;
    private javax.swing.JCheckBox Topico5;
    // End of variables declaration//GEN-END:variables
}
