package paneles;
import javax.swing.JOptionPane;

/**
 * Clase que se encarga de añadir el proyecto actual al usuario y lo sobreescribe
 */
public class SubirProyecto extends ContenidoPanel {

    /**
     * Constructor de la interfaz de usuario de SubirProyecto
     * @param ventana
     */
    public SubirProyecto(ContenidoJFrame ventana) {
        super(ventana);
        initComponents();
    }
    
    /**
     * Método que se encarga de validar los datos del formulario
     */
    private void validarFormulario() {
        Usuario temporal = this.getChambapp().getUsuarioActual();
        if(Nombre.getText().equals("") || Descripcion.getText().equals("") || (float)Monto.getValue() == 0)
            JOptionPane.showMessageDialog(null, "Falta Introducir Datos", "Error", JOptionPane.WARNING_MESSAGE);
        else {
            Proyecto temp = new Proyecto(Nombre.getText(), Descripcion.getText(), Empresa.isSelected(),(float)Monto.getValue());
            temporal.setProyecto(temp);
            Archivo fichero = new Archivo(temporal.getNombre());
            fichero.eliminaArchivo();
            fichero = new Archivo(temporal);
            fichero.escribeArchivo();
            JOptionPane.showMessageDialog(null, "Proyecto Agregado Correctamente", "", JOptionPane.INFORMATION_MESSAGE);
            Utilerias.cambiaComponentePadre(this);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JLabel();
        TDescripcion = new javax.swing.JLabel();
        Instrucciones = new javax.swing.JLabel();
        Enviar = new javax.swing.JButton();
        DescipcionMonto = new javax.swing.JLabel();
        TMonto = new javax.swing.JLabel();
        Monto = new javax.swing.JSpinner();
        Descripcion = new javax.swing.JTextField();
        TEmpresa = new javax.swing.JLabel();
        Empresa = new javax.swing.JCheckBox();
        TNombre = new javax.swing.JLabel();
        Nombre = new javax.swing.JTextField();

        Titulo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("Subir proyecto");

        TDescripcion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TDescripcion.setText("Descripción general");

        Instrucciones.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        Instrucciones.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Instrucciones.setText("Complete los siguientes campos para realizar su búsqueda");

        Enviar.setText("Subir proyecto");
        Enviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnviarActionPerformed(evt);
            }
        });

        DescipcionMonto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DescipcionMonto.setText("Monto solicitado para financiar proyecto");

        TMonto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TMonto.setText("Monto");

        Monto.setModel(new javax.swing.SpinnerNumberModel(0.0f, 0.0f, null, 1.0f));

        TEmpresa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TEmpresa.setText("Es una empresa ya constituida, con menos de 2 años de actividad");

        Empresa.setText("Sí");

        TNombre.setText("Nombre Proyecto: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TDescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(427, 427, 427))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(176, 176, 176)
                                .addComponent(Enviar))
                            .addComponent(Titulo)
                            .addComponent(Instrucciones))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TMonto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Monto, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(DescipcionMonto)
                            .addComponent(TEmpresa)
                            .addComponent(Empresa)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TNombre)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Instrucciones)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TNombre)
                    .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TDescripcion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DescipcionMonto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Monto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TMonto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TEmpresa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Empresa)
                .addGap(5, 5, 5)
                .addComponent(Enviar)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Método encargado de ejecutar la accion posterior al clic en el botón enviar
     * @param evt Escuchador
     */
    private void EnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnviarActionPerformed
        validarFormulario();
    }//GEN-LAST:event_EnviarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DescipcionMonto;
    private javax.swing.JTextField Descripcion;
    private javax.swing.JCheckBox Empresa;
    private javax.swing.JButton Enviar;
    private javax.swing.JLabel Instrucciones;
    private javax.swing.JSpinner Monto;
    private javax.swing.JTextField Nombre;
    private javax.swing.JLabel TDescripcion;
    private javax.swing.JLabel TEmpresa;
    private javax.swing.JLabel TMonto;
    private javax.swing.JLabel TNombre;
    private javax.swing.JLabel Titulo;
    // End of variables declaration//GEN-END:variables
}
